name: async_signal
description: Control the flow of asynchronous operations by signaling all the waiting tasks whether they should wait or continue at a specific point. Lock and unlock the flow.
version: 0.0.4
repository: https://github.com/DrafaKiller/AsyncSignal-dart
issue_tracker: https://github.com/DrafaKiller/AsyncSignal-dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'