name: async_signal
description: Control the flow of asynchronous operations by signaling all the waiting tasks whether they should wait or continue at a specific point. Lock and unlock the flow.
version: 0.0.2
homepage: https://github.com/DrafaKiller/AsyncSignal-dart

environment:
  sdk: '>=2.17.1 <3.0.0'